//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elements
    {
        public int Id { get; set; }
        public string intitule { get; set; }
        public string reponses { get; set; }
        public string media { get; set; }
        public string couleur { get; set; }
        public string doc { get; set; }
        public Nullable<int> ChoixId { get; set; }
        public Nullable<int> TypeElement_Id { get; set; }
        public Nullable<int> questionnaire_id { get; set; }
        public string texte { get; set; }
        public Nullable<int> ordre { get; set; }
    
        public virtual Choixes Choixes { get; set; }
        public virtual Questionnaires Questionnaires { get; set; }
        public virtual TypeElements TypeElements { get; set; }
    }
}
