//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupeSiteQuestionnaire
    {
        public int Id { get; set; }
        public Nullable<int> site_id { get; set; }
        public Nullable<int> questionnaire_id { get; set; }
    
        public virtual Questionnaires Questionnaires { get; set; }
        public virtual Site Site { get; set; }
    }
}
