//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QCMApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reponses
    {
        public int Id { get; set; }
        public int idQuestionnaire { get; set; }
        public string intituleQuestionnaire { get; set; }
        public int idElement { get; set; }
        public string intituleElement { get; set; }
        public int idChoix { get; set; }
        public string intituleChoix { get; set; }
        public bool statut { get; set; }
        public System.DateTime date { get; set; }
        public int UtilisateurId { get; set; }
    
        public virtual Utilisateurs Utilisateurs { get; set; }
    }
}
